title: Wales Gene Park
email: info@walesgenepark.com
description: >-
  Advancing genomic medicine through research, education, and clinical services.
baseurl: ""
url: "https://walesgenepark.com"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

permalink: /:lang/:categories/:title/

# Multilingual settings
languages: ["en", "cy"]
default_lang: "en"
exclude_from_localization: ["assets", "css", "js", "images"]
parallel_localization: true

# Collections
collections:
  posts:
    output: true


# Defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      lang: "en"
  -
    scope:
      path: "_posts"
    values:
      layout: "post"
      lang: "en"