baseURL = "https://walesgenepark.github.io/"
title = "Wales Gene Park"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[languages]
  [languages.en]
    languageName = "English"
    contentDir = "content/english"
    weight = 1
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "home"
        name = "HOME"
        url = "/"
        weight = 1
      [[languages.en.menu.main]]
        identifier = "news"
        name = "LATEST NEWS"
        url = "/news/"
        weight = 2
      [[languages.en.menu.main]]
        identifier = "about"
        name = "ABOUT US"
        url = "/about/"
        weight = 3
      [[languages.en.menu.main]]
        identifier = "services"
        name = "OUR GENOMICS SERVICES"
        url = "/services/"
        weight = 4
      [[languages.en.menu.main]]
        identifier = "teams"
        name = "OUR TEAMS"
        url = "/teams/"
        weight = 5
      [[languages.en.menu.main]]
        identifier = "contact"
        name = "CONTACT US"
        url = "/contact/"
        weight = 6
      [[languages.en.menu.main]]
        identifier = "events"
        name = "EVENTS"
        url = "/events/"
        weight = 7

  [languages.cy]
    languageName = "Cymraeg"
    contentDir = "content/welsh"
    weight = 2
    [languages.cy.menu]
      [[languages.cy.menu.main]]
        identifier = "home"
        name = "HAFAN"
        url = "/cy/"
        weight = 1
      [[languages.cy.menu.main]]
        identifier = "news"
        name = "NEWYDDION DIWEDDARAF"
        url = "/cy/news/"
        weight = 2
      [[languages.cy.menu.main]]
        identifier = "about"
        name = "AMDONOM NI"
        url = "/cy/about/"
        weight = 3
      [[languages.cy.menu.main]]
        identifier = "services"
        name = "EIN GWASANAETHAU GENOMEG"
        url = "/cy/services/"
        weight = 4
      [[languages.cy.menu.main]]
        identifier = "teams"
        name = "EIN TIMAU"
        url = "/cy/teams/"
        weight = 5
      [[languages.cy.menu.main]]
        identifier = "contact"
        name = "CYSLLTU â NI"
        url = "/cy/contact/"
        weight = 6
      [[languages.cy.menu.main]]
        identifier = "events"
        name = "DIGWYDDIAU"
        url = "/cy/events/"
        weight = 7

[params]
  description = "Wales Gene Park - Advancing Genetic and Genomic Medicine"
  images = ["images/logo.png"]
  author = "Wales Gene Park"
  github = "https://github.com/yourgithubusername/wales-gene-park"
  twitter = "https://twitter.com/WalesGenePark"

[permalinks]
  news = "/:slug/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[privacy]
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]

[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false
  disableJSON = false
  disableSVG = false
  disableXML = false
  minifyOutput = true