site:
  name: Wales Gene Park
  site: 'https://walesgenepark.github.io'
  base: '/'
  trailingSlash: false
  logo:
    path: '/src/assets/images/wgp-logo.jpg'
    alt: 'Wales Gene Park Logo'

  googleSiteVerificationId: ''

# Default SEO metadata
metadata:
  title:
    default: Wales Gene Park
    template: '%s — Wales Gene Park'
  description: 'Wales Gene Park is a leading organization in genomics research and education, supporting healthcare professionals, researchers, and the public in understanding and advancing genetic medicine.'
  robots:
    index: true
    follow: true
  openGraph:
    site_name: Wales Gene Park
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: '@WalesGenePark'
    site: '@WalesGenePark'
    cardType: summary_large_image

i18n:
  defaultLanguage: 'en'
  languages:
    en:
      name: 'English'
      root: '/'
    cy:
      name: 'Cymraeg'
      root: '/cy'
  textDirection: ltr

analytics:
  vendors:
    googleAnalytics:
      id: null # or "G-XXXXXXXXXX"

ui:
  theme: 'system' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
